UPDATE player SET identifier='novakdjokovic' WHERE last_name = 'Djokovic';
UPDATE player SET identifier='carlosalcaraz' WHERE last_name = 'Alcaraz';
UPDATE player SET identifier='janniksinner' WHERE last_name = 'Sinner';
UPDATE player SET identifier='daniilmedvedev' WHERE last_name = 'Medvedev';
UPDATE player SET identifier='andreyrublev' WHERE last_name = 'Rublev';
UPDATE player SET identifier='alexanderzverev' WHERE last_name = 'Zverev';
UPDATE player SET identifier='holgerrune' WHERE last_name = 'Rune';
UPDATE player SET identifier='huberthurkacz' WHERE last_name = 'Hurkacz';
UPDATE player SET identifier='alexdeminaur' WHERE last_name = 'De Minaur';
UPDATE player SET identifier='taylorfritz' WHERE last_name = 'Fritz';